
services:
  web:
    build: .
    command: ./boot.sh
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env
       
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: